REPOSITORY = 'Repository'
TITLE = 'Title'
DESTINATION_BRANCH = 'Destination branch'
ORIGIN_BRANCH = 'Origin branch'
OPEN_TASK = 'Open task'
RESOLVED_TASK = 'Resolved tasks'
COMMENTS = 'Comments'
HIGH_TAG = 'High'
MEDIUM_TAG = 'Medium'
LOW_TAG = 'Low'
HEADERS = [REPOSITORY, TITLE, DESTINATION_BRANCH, ORIGIN_BRANCH,
           OPEN_TASK, RESOLVED_TASK, COMMENTS, HIGH_TAG, MEDIUM_TAG, LOW_TAG]
